cart/urls.py
from django.urls import path

from . import views
app_name = "cart"

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail'),
    path('push/(?P<pid>\d+)/', views.CartPushView.as_view(), name='cart_push'),
    path('pop/(?P<pid>\d+)/', views.CartPopView.as_view(), name='cart_pop'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

shop/urls.py
from django.urls import path

from . import views
app_name = "shop"
urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list_all'),
    path('(?P<slug>[-\w]+)/', views.ProductListView.as_view(), name='product_list_cat'),
    path('<int:id>/(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name='product_detail'),
    ]

store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url
from django.conf.urls import  include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("cart/", include('cart.urls')),
    path("order/", include('order.urls')),
    path("", include('shop.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]
class CartForm(forms.Form):
    num = forms.TypedChoiceField(label="購買數量", choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

cart/views.py
#參考https://github.com/PacktPublishing/Django-4-by-example

from django.shortcuts import redirect, get_object_or_404
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from shop.models import Product
from .cart import Cart
from .forms import CartForm

class CartPushView(LoginRequiredMixin, FormView):
    form_class = CartForm
    template_name = 'cart_detail.html'
    login_url = '/accounts/login/'
    success_url = '/cart/'
    def form_valid(self, form):
        cart = Cart(self.request)
        product = get_object_or_404(Product, id=self.kwargs['pid'])
        quantity = form.cleaned_data['num']
        cart.push(product, num=quantity)
        return redirect('cart:cart_detail')

class CartPopView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'
    success_url = '/cart/'
    def get(self, request, *args, **kwargs):
        pid = kwargs.get('pid')
        cart = Cart(request)
        product = get_object_or_404(Product, id=pid)
        if str(product.id) in cart.cart:
            cart.pop(product)
        return redirect('cart:cart_detail')

class CartDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'cart_detail.html'
    login_url = '/accounts/login/'
    success_url = '/cart/'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request)
        for item in cart:  #呼叫__iter__
            item['num_form'] = CartForm(initial={'num': item['num']})
        context['cart'] = cart
        return context

cart/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}
{% block title %}
    購物車
{% endblock %}

{% block content %}
    <h1>購物車</h1>

    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table">
                <thead>
                <tr>
                    <th>商品</th>
                    <th class="text-center">數量</th>
                    <th class="text-center">商品價格</th>
                    <th class="text-center">商品總價</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td class="col-sm-6 col-md-4">
                                <div class="media">
                                    <img class="media-object thumbnail pull-left"
                                        src="{% if product.image %}{{ product.image.url }}
                                             {% else %}{% static "img/product.png" %}{% endif %}"
                                             style="width: 72px; height: 72px;">
                                    <div class="media-body">
                                        <h4>{{ product.name }}</h4>
                                        <span>狀態: </span><span class="text-info"><strong>有存貨</strong></span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-2 col-md-2" style="text-align: center">
                                <form class="form-inline" action="{% url "cart:cart_push" product.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                    {% bootstrap_field item.num_form.num show_label=False %}
                                    </div>
                                    <div class="form-group">
                                    {% buttons %}
                                        <button type="submit" class="btn btn-success">
                                            更新數量
                                        </button>
                                    {% endbuttons %}
                                    </div>
                                </form>
                            </td>

                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.price }}</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>${{ item.tprice }}</strong></td>

                            <td class="col-sm-1 col-md-1">
                                <a href="{% url "cart:cart_pop" product.id %}" class="btn btn-danger">
                                    <i class="glyphicon glyphicon-trash" aria-hidden="true"></i> 刪除
                                </a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>總金額</h3></td>
                    <td class="text-right"><h3><strong>${{ cart.get_tprice }}</strong></h3></td>
                </tr>
                <tr>
                    <td>  </td>
                    <td colspan="2"><h3>
                        <a href="{% url "shop:product_list_all" %}">
                          <i class="glyphicon glyphicon-shopping-cart"></i>繼續購物
                        </a>
                        <a href="{% url "order:checkout" %}">
                          <i class="glyphicon glyphicon-usd"></i>結帳
                        </a>
                        </h3>
                    </td>
                    <td colspan="2">
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}